name: Deploy to main Server

on:
  push:
    branches: main

jobs:
  deploy:
    environment: CONFIG_ENV  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Copy files to SSH Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: '-rlgoDzvc -i --delete'
          SOURCE: './'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ~/app/next/next-app/

      - name: SSH into server instance and start app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/next/next-app/
            docker compose -f docker-compose.dev.yml up --build --force-recreate -d
            docker container prune 
            docker image prune -a -f